language: node_js
node_js:
- stable
install:
- npm install
before_script:
- npm install -save-dev cypress
- npm install -g httpserver
- npm run build
- cd dist && httpserver -p 8080 &
script:
- npm run cypress
