dist: trusty
language: node_js
node_js:
- stable
chche:
  directories:
  - node-modules
before_script:
- npm install -g httpserver
- npm run custom-build
- cd dist && httpserver -p 8080 &
script:
- npm run cypress
