dist: trusty
language: node_js
node_js:
- stable
cache:
  directories:
  - node-modules
before_script:
- npm install script
- npm run dev &
script:
- npm run cypress
deploy:
  provider: surge
  skip_cleanup: true
  domain: onlinelibrary.surge.sh
  project: ./dist
  on:
    branch: master
